package com.ragnarok.auth.common.exception

class HashingException(cause: Throwable) : RuntimeException(cause)
